name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test

      - name: Build Nuxt app
        run: npm run build
        env:
          NUXT_PUBLIC_ENV: ${{ github.ref_name }}

      - name: Deploy to Vercel (Development)
        if: github.ref == 'refs/heads/development'
        run: |
          npx vercel deploy --prod --token $VERCEL_TOKEN --env NUXT_PUBLIC_ENV=development

      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          npx vercel deploy --prod --token $VERCEL_TOKEN --env NUXT_PUBLIC_ENV=production
